### ISSUE TITLE
Erro ao gerar backup

### ISSUE THREAD

**Issue by marceloakira** [cercomp/weby#275]
1) DESCRIÇÃO:
Ao gerar o backup (/admin/backups), acionando o botão 'gerar', a seguinte mensagem de erro aparece:
Ocorreu um erro interno no servidor
14654856848

2) DIAGNÓSTICO:
No arquivo error.log aparece a seguinte mensagem:
/app/controllers/sites/admin/backups_controller.rb:40:in `initialize'
/app/controllers/sites/admin/backups_controller.rb:40:in `open'
/app/controllers/sites/admin/backups_controller.rb:40:in `generate'
2016.flisol.fgsl.net/admin/generate?utf8=%E2%9C%93&type=JSON&pages=1&news=1&repositories=1&menus=1&themes=1&banners=1&extensions=1&commit=+Gerar+ from 179.187.172.86
{"utf8"=>"✓", "type"=>"JSON", "pages"=>"1", "news"=>"1", "repositories"=>"1", "menus"=>"1", "themes"=>"1", "banners"=>"1", "extensions"=>"1", "commit"=>" Gerar ", "controller"=>"sites/admin/backups", "action"=>"generate", "per_page"=>25}
}{14654849821:2016-06-09 12:09:42 -0300
Fórum Goiano de Software Livre
Errno::ENOENT
No such file or directory @ rb_sysopen - /var/www/weby/tmp/2/2016.xml

Criei o diretório '2' manualmente e a mensagem de erro no navegador permanece o mesmo, no entanto, no diretório recém criado, é encontrado o arquivo 2016.xml, a mensagem no error.log permanece quase a mesma:

/app/controllers/sites/admin/backups_controller.rb:40:in `initialize'
/app/controllers/sites/admin/backups_controller.rb:40:in `open'
/app/controllers/sites/admin/backups_controller.rb:40:in `generate'
2016.flisol.fgsl.net/admin/generate?utf8=%E2%9C%93&type=JSON&pages=1&news=1&repositories=1&menus=1&themes=1&banners=1&extensions=1&commit=+Gerar+ from 179.187.172.86
{"utf8"=>"✓", "type"=>"JSON", "pages"=>"1", "news"=>"1", "repositories"=>"1", "menus"=>"1", "themes"=>"1", "banners"=>"1", "extensions"=>"1", "commit"=>" Gerar ", "controller"=>"sites/admin/backups", "action"=>"generate", "per_page"=>25}
}{14654849821:2016-06-09 12:09:42 -0300
Fórum Goiano de Software Livre
Errno::ENOENT
No such file or directory @ rb_sysopen - /var/www/weby/tmp/2/2016.xml

**Comment by marceloakira** [comment]
Caros, o erro ocorreu novamente, segue o log:
Fórum Goiano de Software Livre
Errno::ENOENT
No such file or directory @ rb_file_s_lstat - tmp/2/2016.json
/app/controllers/sites/admin/backups_controller.rb:64:in `block in generate'
/app/controllers/sites/admin/backups_controller.rb:54:in `generate'
2016.fgsl.net/admin/generate?utf8=%E2%9C%93&type=JSON&pages=1&themes=1&commit=+Gerar+ from 191.191.142.243
{"utf8"=>"✓", "type"=>"JSON", "pages"=>"1", "themes"=>"1", "commit"=>" Gerar ", "controller"=>"sites/admin/backups", "action"=>"generate", "per_page"=>25}
}{14707777557:2016-08-09 18:22:35 -0300
Fórum Goiano de Software Livre
Errno::ENOENT
No such file or directory @ rb_file_s_lstat - tmp/2/2016.json
/app/controllers/sites/admin/backups_controller.rb:64:in `block in generate'
/app/controllers/sites/admin/backups_controller.rb:54:in `generate'
2016.fgsl.net/admin/generate?utf8=%E2%9C%93&type=JSON&pages=1&themes=1&commit=+Gerar+ from 191.191.142.243
{"utf8"=>"✓", "type"=>"JSON", "pages"=>"1", "themes"=>"1", "commit"=>" Gerar ", "controller"=>"sites/admin/backups", "action"=>"generate", "per_page"=>25}
