### ISSUE TITLE
Erro ao gerar backup (de novo)

### ISSUE THREAD

**Issue by marceloakira** [cercomp/weby#284]
Ocorreu um erro semelhante ao (#275):
- Na página, o erro apresentado é o seguinte:
```
 Ocorreu um erro interno no servidor

14707780484
Voltar 
```
- E nos logs, temos o seguinte:
```
Fórum Goiano de Software Livre
Errno::ENOENT
No such file or directory @ rb_file_s_lstat - tmp/2/2016.json
/app/controllers/sites/admin/backups_controller.rb:64:in `block in generate'
/app/controllers/sites/admin/backups_controller.rb:54:in `generate'
2016.fgsl.net/admin/generate?utf8=%E2%9C%93&type=JSON&pages=1&themes=1&commit=+Gerar+ from 191.191.142.243
{"utf8"=>"✓", "type"=>"JSON", "pages"=>"1", "themes"=>"1", "commit"=>" Gerar ", "controller"=>"sites/admin/backups", "action"=>"generate", "per_page"=>25}
}{14707777557:2016-08-09 18:22:35 -0300
Fórum Goiano de Software Livre
Errno::ENOENT
No such file or directory @ rb_file_s_lstat - tmp/2/2016.json
/app/controllers/sites/admin/backups_controller.rb:64:in `block in generate'
/app/controllers/sites/admin/backups_controller.rb:54:in `generate'
2016.fgsl.net/admin/generate?utf8=%E2%9C%93&type=JSON&pages=1&themes=1&commit=+Gerar+ from 191.191.142.243
{"utf8"=>"✓", "type"=>"JSON", "pages"=>"1", "themes"=>"1", "commit"=>" Gerar ", "controller"=>"sites/admin/backups", "action"=>"generate", "per_page"=>25}
```

**Comment by leo-souza** [comment]
@marceloakira olá, esse problema ainda existe?
