### ISSUE TITLE
Erro ao iniciar o weby

### ISSUE THREAD

**Issue by marceloakira** [cercomp/weby#285]
O seguinte erro ocorreu ao iniciar o Weby:

```

=> Booting Thin
=> Rails 4.2.5 application starting in production on http://flisol.fgsl.net:3000
=> Run `rails server -h` for more startup options
/var/lib/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require': /var/www/weby/app/controllers/sites_controller.rb:96: syntax error, unexpected ':', expecting => (SyntaxError)
      permitted << {"#{shareable}_social_share_networks": []}
                                                         ^
/var/www/weby/app/controllers/sites_controller.rb:101: syntax error, unexpected end-of-input, expecting keyword_end
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /var/lib/gems/2.1.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'

```
Comentei a linha 96 do arquivo /var/www/weby/app/controllers/sites_controller.rb e subiu normalmente, no entanto gostaria de que o problema fosse resolvido definitivamente.

**Comment by leo-souza** [comment]
Esse formato de hash eh suportado a partir do ruby 2.2. Em versões anteriores pode ocorrer esse erro. Mudei o formato para ser compatível.
https://github.com/cercomp/weby/commit/f4bcfb31e2e7d9f1f156dcd24a3b6fc9fd942175
